return {
  "mason-org/mason-lspconfig.nvim",
  event = "BufEnter",
  dependencies = {
    "mason-org/mason.nvim",
    "neovim/nvim-lspconfig",
  },
  opts = {
    ensure_installed = {
      "bashls",
      "clangd",
      "cssls",
      "dockerls",
      "dotls",
      "gopls",
      "html",
      "jsonls",
      "lemminx",
      "lua_ls",
      "omnisharp",
      "powershell_es",
      "pylsp",
      "rust_analyzer",
      "tsgo",
      "vimls",
      "yamlls",
      "zls",
    },
    automatic_enable = true,
    automatic_installation = true,
  },
}
